[account]
private_key = "0x..."

[default_size]
type = "risk" # risk | notional
size = "$15"


[default_leverage]
value = 1 # 1 | 2 | 3 | 4 | 5 | 10 | 25 | 50 | 100

[default_margin]
value = 'isolated' # cross | isolated

[default_asset]
value = 'USDT' # USDT | BUSD | BNB | BTC | ETH | ...
