[network]
api = "https://api.hyperliquid-testnet.xyz"

[account]
private_key = "0x..."

[default_size]
type = "risk" # risk | notional
value = "15"  # 15 | 20 | 2% | 5% 


[default_margin]
value = 'isolated' # cross | isolated

[default_asset]
value = 'USDT' # USDT | BUSD | BNB | BTC | ETH | ...
